"""mudanca email

Revision ID: 782129f1830e
Revises: 6bed308d2377
Create Date: 2022-05-22 17:58:34.550306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '782129f1830e'
down_revision = '6bed308d2377'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'empresas', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'empresas', type_='unique')
    # ### end Alembic commands ###
