"""conserto banco dados e  conversao

Revision ID: 9b0e871dd12a
Revises: e7aa8535f9b9
Create Date: 2022-05-28 20:35:48.182043

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9b0e871dd12a'
down_revision = 'e7aa8535f9b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ConversoesColaboradores',
    sa.Column('idColaborador', sa.Integer(), nullable=False),
    sa.Column('idDadosConversao', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idColaborador'], ['Colaboradores.id'], ),
    sa.ForeignKeyConstraint(['idDadosConversao'], ['DadosConversao.id'], ),
    sa.PrimaryKeyConstraint('idColaborador', 'idDadosConversao')
    )
    op.drop_table('ConversaoColaboradore')
    op.add_column('DadosConversao', sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('DadosConversao', 'salarioInserido',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('DadosConversao', 'salarioConvertido',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('DadosConversao', 'salarioDescontado',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('DadosConversao', 'salarioRetornado',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('DadosConversao', 'imposto',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('DadosConversao', 'moeda',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('DadosConversao', 'date')
    op.drop_column('DadosConversao', 'horas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DadosConversao', sa.Column('horas', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('DadosConversao', sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('DadosConversao', 'moeda',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('DadosConversao', 'imposto',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('DadosConversao', 'salarioRetornado',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('DadosConversao', 'salarioDescontado',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('DadosConversao', 'salarioConvertido',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('DadosConversao', 'salarioInserido',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('DadosConversao', 'time_created')
    op.create_table('ConversaoColaboradore',
    sa.Column('IdDadosConversao', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('idColaborador', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['IdDadosConversao'], ['DadosConversao.id'], name='ConversaoColaboradore_IdDadosConversao_fkey'),
    sa.ForeignKeyConstraint(['idColaborador'], ['Colaboradores.id'], name='ConversaoColaboradore_idColaborador_fkey')
    )
    op.drop_table('ConversoesColaboradores')
    # ### end Alembic commands ###
