"""tabela de Colaboradore Dados de Coversao

Revision ID: e7aa8535f9b9
Revises: 76cec8b46141
Create Date: 2022-05-26 21:44:53.343392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7aa8535f9b9'
down_revision = '76cec8b46141'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Colaboradores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Colaboradores_email'), 'Colaboradores', ['email'], unique=True)
    op.create_index(op.f('ix_Colaboradores_id'), 'Colaboradores', ['id'], unique=False)
    op.create_table('DadosConversao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salarioInserido', sa.Float(), nullable=False),
    sa.Column('salarioConvertido', sa.Float(), nullable=False),
    sa.Column('salarioDescontado', sa.Float(), nullable=False),
    sa.Column('salarioRetornado', sa.Float(), nullable=False),
    sa.Column('imposto', sa.Float(), nullable=False),
    sa.Column('moeda', sa.Float(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('horas', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_DadosConversao_id'), 'DadosConversao', ['id'], unique=False)
    op.create_table('ConversaoColaboradore',
    sa.Column('IdDadosConversao', sa.Integer(), nullable=True),
    sa.Column('idColaborador', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['IdDadosConversao'], ['DadosConversao.id'], ),
    sa.ForeignKeyConstraint(['idColaborador'], ['Colaboradores.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ConversaoColaboradore')
    op.drop_index(op.f('ix_DadosConversao_id'), table_name='DadosConversao')
    op.drop_table('DadosConversao')
    op.drop_index(op.f('ix_Colaboradores_id'), table_name='Colaboradores')
    op.drop_index(op.f('ix_Colaboradores_email'), table_name='Colaboradores')
    op.drop_table('Colaboradores')
    # ### end Alembic commands ###
